
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/Users/natalia/miniforge3/bin/"
      - "/Users/natalia/miniforge3/condabin/"
      - "/Library/TeX/texbin/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/opt/local/bin/"
      - "/opt/local/sbin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/Library/Apple/usr/bin/"
    searched_directories:
      - "/Users/natalia/miniforge3/bin/uname"
      - "/Users/natalia/miniforge3/condabin/uname"
      - "/Library/TeX/texbin/uname"
      - "/opt/homebrew/bin/uname"
      - "/opt/homebrew/sbin/uname"
      - "/opt/local/bin/uname"
      - "/opt/local/sbin/uname"
      - "/usr/local/bin/uname"
      - "/System/Cryptexes/App/usr/bin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/Users/natalia/miniforge3/bin"
        - "/Users/natalia/miniforge3/condabin"
        - "/Library/TeX/texbin"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/opt/local/bin"
        - "/opt/local/sbin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/Library/TeX/texbin"
        - "/Library/Apple/usr/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Darwin - 22.1.0 - arm64
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/Platform/Darwin.cmake:76 (find_program)"
      - "/opt/homebrew/share/cmake/Modules/CMakeSystemSpecificInformation.cmake:32 (include)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_INSTALL_NAME_TOOL"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "install_name_tool"
    candidate_directories:
      - "/Users/natalia/miniforge3/bin/"
      - "/Users/natalia/miniforge3/condabin/"
      - "/Library/TeX/texbin/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/opt/local/bin/"
      - "/opt/local/sbin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/Library/Apple/usr/bin/"
    searched_directories:
      - "/Users/natalia/miniforge3/bin/install_name_tool"
      - "/Users/natalia/miniforge3/condabin/install_name_tool"
      - "/Library/TeX/texbin/install_name_tool"
      - "/opt/homebrew/bin/install_name_tool"
      - "/opt/homebrew/sbin/install_name_tool"
      - "/opt/local/bin/install_name_tool"
      - "/opt/local/sbin/install_name_tool"
      - "/usr/local/bin/install_name_tool"
      - "/System/Cryptexes/App/usr/bin/install_name_tool"
    found: "/usr/bin/install_name_tool"
    search_context:
      ENV{PATH}:
        - "/Users/natalia/miniforge3/bin"
        - "/Users/natalia/miniforge3/condabin"
        - "/Library/TeX/texbin"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/opt/local/bin"
        - "/opt/local/sbin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/Library/TeX/texbin"
        - "/Library/Apple/usr/bin"
      CMAKE_INSTALL_PREFIX: "/usr/local"
...
